/**
 * Pixel sprites drawn in code. Each sprite is a character grid plus a
 * palette; '.' is transparent. Rendered as SVG rects with crisp edges.
 * Deliberately simple — charm over fidelity (PRD §5).
 */
export interface SpriteDef {
  palette: Record<string, string>
  rows: string[]
}

const S = (palette: Record<string, string>, rows: string[]): SpriteDef => ({ palette, rows })

export const SPRITES: Record<string, SpriteDef> = {
  tv: S(
    { k: '#2b2b33', s: '#7fd4e8', h: '#e8f8ff', l: '#55585f', f: '#3a3d44' },
    [
      'kkkkkkkkkkkk',
      'kssssssssssk',
      'kshhsssssssk',
      'kssssssssssk',
      'kssssssssssk',
      'kkkkkkkkkkkk',
      '....llll....',
      '..ffffffff..',
    ],
  ),
  sofa: S(
    { r: '#c4564a', d: '#9e4036', c: '#d97a6c', w: '#6b4a32' },
    [
      'r..........r',
      'rr........rr',
      'rccccccccccr',
      'rccccccccccr',
      'rrrrrrrrrrrr',
      'rddddddddddr',
      'rddddddddddr',
      '.w........w.',
    ],
  ),
  bed: S(
    { h: '#8a5a3a', b: '#a9714b', s: '#f3ead4', p: '#e8c8c8', d: '#c4564a' },
    [
      'h...........',
      'h...........',
      'hpp.........',
      'hppssssssssh',
      'hddddddddddh',
      'hddddddddddh',
      'bbbbbbbbbbbb',
      'b..........b',
    ],
  ),
  wardrobe: S(
    { w: '#8a5a3a', d: '#a9714b', k: '#3a2a1a', l: '#c79a6b' },
    [
      'wwwwwwwwwww',
      'wddddwddddw',
      'wdddkwkdddw',
      'wddddwddddw',
      'wddddwddddw',
      'wddddwddddw',
      'wllllwllllw',
      'wwwwwwwwwww',
    ],
  ),
  lamp: S(
    { s: '#e8b94a', g: '#f7dc8e', p: '#6b4a32', b: '#574033' },
    [
      '..ssssss..',
      '.sggggggs.',
      'ssggggggss',
      '....pp....',
      '....pp....',
      '....pp....',
      '...bbbb...',
      '..bbbbbb..',
    ],
  ),
  console: S(
    { k: '#3a3d44', l: '#55585f', g: '#7fe87f', b: '#2b2b33' },
    [
      '..........',
      '..........',
      '..........',
      'bbbbbbbbbb',
      'bkkkkkkkkb',
      'bkkglkkkkb',
      'bbbbbbbbbb',
      '..........',
    ],
  ),
  bookshelf: S(
    { w: '#8a5a3a', r: '#c4564a', g: '#6e9e5b', b: '#5b7e9e', y: '#e8b94a' },
    [
      'wwwwwwwwww',
      'wrgbyrgbyw',
      'wwwwwwwwww',
      'wygrbygrbw',
      'wwwwwwwwww',
      'wbryggbryw',
      'wwwwwwwwww',
      'w........w',
    ],
  ),
  oven: S(
    { m: '#c9c9bf', k: '#3a3d44', g: '#55585f', o: '#e8964a', h: '#e8e6d4' },
    [
      'mmmmmmmmmm',
      'mkkhmmhkkm',
      'mmmmmmmmmm',
      'mkkkkkkkkm',
      'mkggggggkm',
      'mkgoooogkm',
      'mkkkkkkkkm',
      'mmmmmmmmmm',
    ],
  ),
  hob: S(
    { m: '#3a3d44', r: '#c4564a', k: '#2b2b33' },
    [
      '..........',
      '..........',
      '..........',
      '..........',
      '..........',
      'kkkkkkkkkk',
      'krrkkrrkkk',
      'mmmmmmmmmm',
    ],
  ),
  fridge: S(
    { m: '#e8e6d4', s: '#cfcdb8', k: '#9c9c90', h: '#55585f' },
    [
      'mmmmmmmm',
      'mssssssm',
      'mhsssssm',
      'mmmmmmmm',
      'mhsssssm',
      'mssssssm',
      'mssssssm',
      'mmmmmmmm',
    ],
  ),
  dishwasher: S(
    { m: '#cfcdb8', k: '#3a3d44', g: '#7fd4e8', s: '#9c9c90' },
    [
      'mmmmmmmmmm',
      'mkkmmmmssm',
      'mmmmmmmmmm',
      'mggggggggm',
      'mggggggggm',
      'mssssssssm',
      'mssssssssm',
      'mmmmmmmmmm',
    ],
  ),
  washing_machine: S(
    { m: '#e8e6d4', k: '#3a3d44', g: '#7fd4e8', w: '#e8f8ff', s: '#9c9c90' },
    [
      'mmmmmmmmmm',
      'mkkmmmmssm',
      'mmmmmmmmmm',
      'mmmkkkkmmm',
      'mmkggggkmm',
      'mmkgwggkmm',
      'mmmkkkkmmm',
      'mmmmmmmmmm',
    ],
  ),
  tumble_dryer: S(
    { m: '#cfcdb8', k: '#3a3d44', g: '#d9b98c', w: '#f3e3c3', s: '#9c9c90' },
    [
      'mmmmmmmmmm',
      'mssmmmmkkm',
      'mmmmmmmmmm',
      'mmmkkkkmmm',
      'mmkggggkmm',
      'mmkgwggkmm',
      'mmmkkkkmmm',
      'mmmmmmmmmm',
    ],
  ),
  microwave: S(
    { m: '#3a3d44', k: '#2b2b33', g: '#f7dc8e', s: '#55585f' },
    [
      '..........',
      '..........',
      '..........',
      'mmmmmmmmmm',
      'mkkkkkkmsm',
      'mkggggkmsm',
      'mkkkkkkmsm',
      'mmmmmmmmmm',
    ],
  ),
  kettle: S(
    { m: '#9fbcb6', k: '#3a3d44', h: '#d3e7e3' },
    [
      '..........',
      '..........',
      '..........',
      '...mmmm.k.',
      '..mhmmmmk.',
      '..mmmmmmk.',
      '...mmmm...',
      '..kkkkkk..',
    ],
  ),
  boiler: S(
    { m: '#e8e6d4', s: '#cfcdb8', k: '#3a3d44', f: '#e8964a', b: '#7fd4e8' },
    [
      'mmmmmmmm',
      'mssssssm',
      'mskkkksm',
      'mskfbksm',
      'mskkkksm',
      'mssssssm',
      'mmmmmmmm',
      '.k....k.',
    ],
  ),
  shower: S(
    { m: '#9c9c90', g: '#d3e7e3', w: '#7fd4e8', k: '#55585f' },
    [
      'mmmmmmmm',
      'm.kkk...',
      'm.w.w.w.',
      'm.......',
      'm.w.w.w.',
      'm.......',
      'm.w.w.w.',
      'mggggggg',
    ],
  ),
  bath: S(
    { w: '#e8f8ff', b: '#d3e7e3', s: '#9fbcb6', k: '#55585f' },
    [
      '..........',
      '..k.......',
      '..k.......',
      'bwwwwwwwwb',
      'bbbbbbbbbb',
      'bbbbbbbbbb',
      '.ss....ss.',
      '.ss....ss.',
    ],
  ),
  toilet: S(
    { w: '#f4f4f0', s: '#d8d8d0', k: '#9c9c90' },
    [
      '.www......',
      '.www......',
      '.wwwwwww..',
      '.wsssssw..',
      '..wwwww...',
      '...www....',
      '...www....',
      '..wwwww...',
    ],
  ),
  extractor_fan: S(
    { m: '#cfcdb8', k: '#55585f', f: '#9c9c90' },
    [
      'mmmmmmmm',
      'mffkkffm',
      'mfkkkkfm',
      'mkkffkkm',
      'mkkffkkm',
      'mfkkkkfm',
      'mffkkffm',
      'mmmmmmmm',
    ],
  ),
  desk: S(
    { w: '#8a5a3a', l: '#a9714b' },
    [
      '..........',
      '..........',
      '..........',
      '..........',
      'wwwwwwwwww',
      'l..l..l..l',
      'l........l',
      'l........l',
    ],
  ),
  computer: S(
    { k: '#3a3d44', s: '#55585f', g: '#7fe87f' },
    [
      '...kkkk...',
      '...ksgk...',
      '...kssk...',
      '...kssk...',
      '...kkkk...',
      '..........',
      '..........',
      '..........',
    ],
  ),
  monitor: S(
    { k: '#2b2b33', s: '#5b7e9e', h: '#9ec5e8', l: '#55585f' },
    [
      'kkkkkkkkkk',
      'kssssssssk',
      'kshhsssssk',
      'kssssssssk',
      'kkkkkkkkkk',
      '....ll....',
      '...llll...',
      '..........',
    ],
  ),
  printer: S(
    { m: '#d8d4cc', k: '#3a3d44', p: '#f4f4f0', s: '#9c9c90' },
    [
      '..........',
      '..........',
      '..ppppp...',
      'mmmmmmmmmm',
      'mkmmmmmmsm',
      'mmmppppmmm',
      'mmmppppmmm',
      'mmmmmmmmmm',
    ],
  ),
  lawnmower: S(
    { g: '#6e9e5b', k: '#2b2b33', m: '#9c9c90', r: '#c4564a' },
    [
      '........m.',
      '.......m..',
      '......m...',
      '.....m....',
      'rrrrrm....',
      'rrrrrr....',
      'kk..kk....',
      'kk..kk....',
    ],
  ),
  bbq: S(
    { k: '#2b2b33', m: '#3a3d44', f: '#e8964a', s: '#55585f' },
    [
      '..f.f.....',
      '.f.f.f....',
      'mmmmmmm...',
      'mkkkkkm...',
      'mmmmmmm...',
      '..s.s.....',
      '..s.s.....',
      '.ss.ss....',
    ],
  ),
  sauna: S(
    { w: '#c8a276', d: '#a9825a', k: '#3a2a1a', s: '#e8e6d4' },
    [
      '.wwwwwwww.',
      'wwwwwwwwww',
      'wddddddddw',
      'wdkkdssddw',
      'wdkkdssddw',
      'wddddddddw',
      'wddddddddw',
      'wwwwwwwwww',
    ],
  ),
  garden_furniture: S(
    { w: '#c8a276', d: '#a9825a' },
    [
      '..........',
      '..........',
      'd...ww...d',
      'd..wwww..d',
      'dwwwwwwwwd',
      'd...ww...d',
      'd..d..d..d',
      'd..d..d..d',
    ],
  ),
  power_tools: S(
    { r: '#c4564a', k: '#2b2b33', m: '#9c9c90', y: '#e8b94a' },
    [
      '..........',
      '..........',
      '.rrrrr....',
      '.rrrrrmmm.',
      '...rr.....',
      '...rr..yy.',
      '..kkkk.yy.',
      '..........',
    ],
  ),
  car: S(
    { b: '#5b7e9e', d: '#46637e', w: '#9ec5e8', k: '#2b2b33', l: '#f7dc8e', g: '#55585f' },
    [
      '....bbbbbbbb....',
      '...bwwbbbbwwb...',
      '..bbwwbbbbwwbb..',
      'bbbbbbbbbbbbbbbb',
      'lbddddddddddddbl',
      'bbbkkbbbbbbkkbbb',
      '..bkggk..bkggk..',
      '...kkk....kkk...',
    ],
  ),
  bike: S(
    { k: '#2b2b33', r: '#c4564a', g: '#55585f' },
    [
      '..r.......',
      '..rr....k.',
      '...r...k..',
      '.kkkrrkkk.',
      'k...rk...k',
      'k..r..r..k',
      'k.r....r.k',
      '.k......k.',
    ],
  ),
  motorbike: S(
    { k: '#2b2b33', r: '#c4564a', g: '#55585f', l: '#f7dc8e' },
    [
      '.......k..',
      '.rr...k...',
      '.rrrrrkk..',
      '..rrrrr.l.',
      '.kk.rr.kk.',
      'k..k..k..k',
      'k..k..k..k',
      '.kk....kk.',
    ],
  ),
  pet: S(
    { f: '#c79a6b', d: '#a9825a', k: '#2b2b33', p: '#e8c8c8' },
    [
      '.f.....f..',
      'ff.....ff.',
      'fffffffff.',
      'fkffffkff.',
      'fffpfffff.',
      'ffffffffff',
      '.ff.ff.ffd',
      '.ff.ff..d.',
    ],
  ),
  smoke_alarm: S(
    { w: '#f4f4f0', s: '#d8d8d0', r: '#c4564a' },
    [
      '..wwww..',
      '.wwwwww.',
      'wwssssww',
      'wws..sww',
      'wwssssww',
      '.wwrwww.',
      '..wwww..',
      '........',
    ],
  ),
  radiator: S(
    { m: '#e8e6d4', s: '#cfcdb8', k: '#9c9c90' },
    [
      '..........',
      '..........',
      'mmmmmmmmmm',
      'msmsmsmsmm',
      'msmsmsmsmm',
      'msmsmsmsmm',
      'mmmmmmmmmm',
      '.k......k.',
    ],
  ),
  other: S(
    { b: '#c8a276', d: '#a9825a', k: '#6b4a32', q: '#574033' },
    [
      'bbbbbbbbbb',
      'bddddddddb',
      'bdd.kk.ddb',
      'bd...k..db',
      'bdd..k..db',
      'bdd.....db',
      'bdd..k..db',
      'bbbbbbbbbb',
    ],
  ),
}

export const spriteFor = (typeKey: string): SpriteDef => SPRITES[typeKey] ?? SPRITES.other
